[keys.normal]
n="move_line_down"
e="move_line_up"
i="move_char_right"

l="insert_mode"
L="insert_at_line_start"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.g]
n="goto_line_start"
o="goto_line_end"

[keys.normal.space.w]
h="jump_view_left"
n="jump_view_down"
e="jump_view_up"
i="jump_view_right"

[keys.normal.C-w]
h="jump_view_left"
n="jump_view_down"
E="join_selections"
"A-E"="join_selections_space"

i="jump_view_up"
I="keep_selections"
"A-I"="remove_selections"

o="jump_view_right"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode

[keys.select]
h="move_char_left"
n="move_line_down"
e="move_line_up"
i="move_char_right"

l="insert_mode"
L="insert_at_line_start"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.z]
n="scroll_down"
e="scroll_up"

[keys.normal.Z]
n="scroll_down"
e="scroll_up"

